---
- name: Setup Web Servers
  hosts: server
  become: yes
  roles:
    - server

- name: Setup Database Servers
  hosts: db
  become: yes
  roles:
    - db

- name: Deploy Laravel Application
  include_tasks: roles/server/tasks/deploy.yml
