name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_NAME: lrv
      DB_USER: lrv
      DB_PASS: lrvpass

    steps:
      - uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt update
        
      - name: Install dependencies
        run: |
          sudo apt install ufw mysql-server -y
          sudo systemctl start mysql

      - name: Setup MySQL database
        run: |
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS lrv;"
          sudo mysql -e "CREATE USER IF NOT EXISTS 'lrv'@'127.0.0.1' IDENTIFIED BY 'lrvpass';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON lrv.* TO 'lrv'@'127.0.0.1';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Setup Ansible
        run: python3 -m pip install --user ansible

      - name: Run Ansible playbook
        run: |
          cat << EOF > hosts
          [server]
          localhost
          EOF
          ansible-playbook -i ./hosts main.yml -e "db_host=$DB_HOST db_name=$DB_NAME db_user=$DB_USER db_pass=$DB_PASS" -c local
      
      - name: Test if application uses MySQL
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e "SHOW TABLES;" $DB_NAME
